apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cafe-ingress
  annotations:
   kubernetes.io/ingress.class: avi
spec:
  rules:
  - host: cafe.tkg.livefire.solutions
    http:
      paths:
      - path: /tea
        pathType: Prefix
        backend:
         service:
          name: tea-svc
          port: 
           number: 80
      - path: /coffee
        pathType: Prefix
        backend:
         service:
          name: coffee-svc
          port: 
           number: 80
